### PR TITLE
Feature/improve dark mode

### PR DESCRIPTION
**Pull request by macbookandrew**
See screenshots:

# Before

before

# After

Screenshot 2023-03-09 at 09 06 08

### CODE REVIEW

**Comment by macbookandrew** [comment]
Also included: 

- Tweaked spacing of tag search field
- Updated spinners to spin clockwise, matching direction of the arrows

**Comment by gizburdt** [comment]
Awesome, thanks!

**Comment by gizburdt** [comment]
Tagged 3.1.0 :)

**Comment by macbookandrew** [comment]
Thanks 😄

**Pull request merged**
